---
- name: download AAP
  hosts: localhost
  vars:
    app_image: "ansible-automation-platform-setup-bundle-2.1.0-1"
    offline_token: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2NDY4Mzk2MzUsImp0aSI6IjI0NzI2NTA2LTkxNjMtNGM3ZC1iMGNiLTNlNTJlOWVkMzZhYSIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpqdXBpdHRtYUByZWRoYXQuY29tIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImNsb3VkLXNlcnZpY2VzIiwibm9uY2UiOiJhMDk4NmJlNi1lM2JjLTQwNmItODU4ZS0wNmJjZjcwYmYxOTkiLCJzZXNzaW9uX3N0YXRlIjoiZTQ5YTA2M2EtMmJmMC00MWUzLThlNmUtOGY1YjA2Y2ExODY2Iiwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MiLCJzaWQiOiJlNDlhMDYzYS0yYmYwLTQxZTMtOGU2ZS04ZjViMDZjYTE4NjYifQ.4YECDftUZVZBbvB_sZpMX468nU6BaywO6dKvjiZYkCg"
  include_role:
    name: ansible.workshops.aap_download
