---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: workshop collection final check
      block:
        - name: run pre-check role to make sure workshop will complete provisioning
          include_role:
            name: ../roles/workshop_check_setup

        - name: download AAP
          include_role:
            name: ../roles/aap_download
      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.  Open an issue on https://github.com/ansible/workshops/issues

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes"
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: ../roles/connectivity_test

- name: wait for all security nodes to have SSH reachability
  hosts: "security_connection_check"
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: ../roles/connectivity_test

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  gather_facts: false
  become: true
  tasks:
    - include_role:
        name: ../roles/user_accounts
    - include_role:
        name: ../roles/common

- name: Configure /etc/hosts
  hosts: 'managed_nodes:control_nodes'
  gather_facts: true
  become: true
  tasks:
    - name: setup /etc/hosts file per student
      copy:
        src: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ username }}-etchosts.txt"
        dest: "/etc/hosts"
        owner: "{{ username }}"
        group: "{{ username }}"

- name: configure ansible control node
  hosts: '*ansible-1'
  gather_facts: true
  become: true
  tasks:
    - include_role:
        name: ../roles/control_node

    - include_role:
        name: ../roles/code_server
      when:
        - code_server is defined
        - code_server
        - controllerinstall is defined
        - controllerinstall

- name: configure private automation hub
  hosts: 'automation_hub'
  gather_facts: true
  become: true
  tasks:
    - include_role:
        name: ../roles/private_automation_hub
      when:
        - automation_hub is defined
        - automation_hub

- name: add dns entires for all student control nodes
  hosts: '*ansible-1'
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: ../roles/aws_dns
      when:
        - dns_type is defined
        - dns_type == "aws"
        - controllerinstall is defined
        - controllerinstall
  tags: control_node

- name: populate automation controller
  hosts: '*ansible-1'
  become: true
  gather_facts: false
  tasks:
    - name: run populate_controller role
      include_role:
        name: ../roles/populate_controller
      when:
        - controllerinstall is defined
        - controllerinstall|bool
        - populatecontroller

- name: print out information for instructor
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: set facts for output
      set_fact:
        summary_information: |
          PROVISIONER SUMMARY
          *******************
          - Workshop name is {{ec2_name_prefix}}
          - Instructor inventory is located at  {{playbook_dir}}/{{ec2_name_prefix}}/instructor_inventory.txt
          - Private key is located at {{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem
          {% if attendance %}
          - {{hostvars['attendance-host'].login_website_information | default("attendance feature is not functioning") }}
          {% endif %}

          FAILURES
          *******************
          {{dns_information}}
          {{callback_information}}
          {{ demo_information }}

    - name: Print Summary Information
      debug:
        msg: "{{ summary_information }}"
